### ISSUE TITLE
Support settings for case sensitivity, regex options

### ISSUE THREAD

**Issue by davidpeckham** [davidpeckham/sublime-filterlines#2]

**Comment by apdp** [comment]
Hi,

That could be nice to add few words in readme.md about these case sensitive options because it's useful when to know it is possible to configure this preference option.

Maybe as an improvement : why not add an argument to override this option too
(so that we could have on key shortcut to filter case sentive, and another key hsortcut to filter case insensitive) - depending on the use we have of course.

cheers
